site_name: decom_py
site_description: EwE model wrapper
site_author: Daniel Tan
site_url: https://open-aims.github.io/decom_py
repo_url: https://github.com/open-AIMS/decom_py

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
  - section-index

nav:
  - Home: index.md
  - User Guide: usage.md
  - High Level Interface: high_level_interface
  - Medium Level Interface: medium_level_interface.md
  - Parameter Management: parameter_management.md
  - API: 
      - Reference: api/reference.md
      - Results: api/results.md
