site_name: decom_py
site_description: EwE model wrapper
site_author: Daniel Tan
site_url: https://open-aims.github.io/decom_py
repo_url: https://github.com/open-AIMS/decom_py

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            merge_init_into_class: true
            show_source: true
            show_root_heading: true
            show_signature_as_heading: true
            show_root_full_path: false
            category_section_style: spacy
            show_root_members_full_path: false

          paths: [./src/.]
  - section-index

nav:
  - Home: index.md
  - High Level Interface: high_level_interface.md
  - Medium Level Interface: medium_level_interface.md
  - Parameter Management: parameter_management.md
  - API: 
      - Reference: api/reference.md
      - Results: api/results.md
  - Development: development.md
